export const GET_APPLICANT_REQUEST="GET_APPLICANT_REQUEST"
export const GET_APPLICANT_SUCCESS="GET_APPLICANT_SUCCESS"
export const GET_APPLICANT_FAILURE="GET_APPLICANT_FAILURE"


export const ADD_REQUEST="ADD_REQUEST"
export const ADD_SUCCESS="ADD_SUCCESS"
export const ADD_FAILURE="ADD_FAILURE"
