export const GET_APPLICANT_REQUEST="GET_APPLICANT_REQUEST"
export const GET_APPLICANT_SUCCESS="GET_APPLICANT_SUCCESS"
export const GET_APPLICANT_FAILURE="GET_APPLICANT_FAILURE"

export const LOGIN_REQUEST="LOGIN_REQUEST";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FALIURE="LOGIN_FALIURE";

export const LOGOUT_REQUEST="LOGOUT_REQUEST";
export const LOGOUT_SUCESS="LOGOUT_SUCESS";
export const LOGOUT_FAILURE="LOGOUT_FAILURE"