export const LOGIN_REQUEST="LOGIN_REQUEST";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FALIURE="LOGIN_FALIURE";

export const LOGOUT_REQUEST="LOGOUT_REQUEST";
export const LOGOUT_SUCESS="LOGOUT_SUCESS";
export const LOGOUT_FAILURE="LOGOUT_FAILURE"